import { AuthProvider } from "@/context/authContext";
import StoreProvider from "@/state/StoreProvider";
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";

import { Toaster } from "@/components/ui/sonner";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AuthProvider>
          <Providers>
            <StoreProvider>{children}</StoreProvider>
            <Toaster />
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
